import { Loader2, Presentation } from "lucide-react";
import { SlideCarousel } from "../features/presentation/PresentationBuilder";
import { useGetPresentation } from "../features/presentation/usePresentation";

interface PresentationViewPageProps {
  shareToken: string;
}

export default function PresentationViewPage({
  shareToken,
}: PresentationViewPageProps) {
  const { data: presentation, isLoading } = useGetPresentation(shareToken);

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="flex flex-col items-center gap-4 text-foreground">
          <Loader2 className="w-10 h-10 animate-spin text-primary" />
          <p className="text-lg font-display">Loading presentation…</p>
        </div>
      </div>
    );
  }

  if (!presentation) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background p-6">
        <div className="text-center max-w-md">
          <div className="w-16 h-16 rounded-full bg-muted flex items-center justify-center mx-auto mb-4">
            <Presentation className="w-8 h-8 text-muted-foreground" />
          </div>
          <h1 className="text-2xl font-display font-bold text-foreground mb-2">
            Presentation Not Found
          </h1>
          <p
            className="text-muted-foreground"
            data-ocid="presentation-not-found"
          >
            This presentation link has expired or is invalid. Ask the driver to
            share a fresh link.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div
      className="min-h-screen bg-background"
      data-ocid="presentation-view-page"
    >
      {/* Branding header */}
      <header className="bg-card border-b border-border px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
              <Presentation className="w-4 h-4 text-primary" />
            </div>
            <span className="font-display font-bold text-foreground">
              MoneyDrive
            </span>
          </div>
          <p className="text-xs text-muted-foreground text-right hidden sm:block">
            This presentation was generated by Nduna for MoneyDrive
          </p>
        </div>
      </header>

      {/* Main content */}
      <main className="max-w-4xl mx-auto px-4 py-8">
        <p className="text-xs text-muted-foreground text-center mb-6 sm:hidden">
          Generated by Nduna AI for MoneyDrive
        </p>
        <SlideCarousel presentation={presentation} readOnly />
      </main>

      {/* Footer */}
      <footer className="border-t border-border bg-card/50 py-6 mt-12">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <p className="text-sm text-muted-foreground">
            © {new Date().getFullYear()}. Built with love using{" "}
            <a
              href={`https://caffeine.ai?utm_source=caffeine-footer&utm_medium=referral&utm_content=${encodeURIComponent(window.location.hostname)}`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              caffeine.ai
            </a>
          </p>
        </div>
      </footer>
    </div>
  );
}
