module {
  /// Variant for recommendation types — replaces free-text recommendationType in NdunaRecommendation.
  public type RecommendationType = {
    #surge;
    #product;
    #advertising;
  };

  /// Confidence level for a Nduna recommendation.
  public type ConfidenceLevel = {
    #HIGH;
    #MEDIUM;
    #LOW;
  };

  /// What action the driver took on a Nduna recommendation.
  public type DriverAction = {
    #tried;    // Driver followed the recommendation
    #skipped;  // Driver did not follow the recommendation
    #partial;  // Driver followed it differently (different time/location)
  };

  /// Extended Nduna recommendation — Text-keyed ID for HashMap storage + proper variants.
  /// Backward-compatible: the original NdunaRecommendation in agent.mo is not removed.
  public type NdunaRecommendationV2 = {
    id : Text;           // Unique Text ID (e.g. UUID or generated key)
    driverId : Text;
    timestamp : Nat64;
    recommendationType : RecommendationType;
    content : Text;      // The recommendation text shown to the driver
    confidence : ConfidenceLevel;
  };

  /// Outcome of a recommendation — recorded by the driver via the feedback card.
  /// revenue is in South African cents (ZAR × 100) to avoid Float precision issues.
  public type RecommendationOutcomeV2 = {
    recommendationId : Text;   // References NdunaRecommendationV2.id
    driverId : Text;
    action : DriverAction;
    revenue : ?Nat;            // In cents (ZAR); null if not applicable or not entered
    notes : ?Text;             // Optional driver notes
    recordedAt : Nat64;
  };

  /// Status of an advertising pitch to a company.
  public type PitchStatus = {
    #sent;        // Pitch was sent to the company
    #viewed;      // Company opened the pitch deck
    #interested;  // Company expressed interest
    #negotiating; // Active deal negotiation in progress
    #closed;      // Deal signed and active
    #rejected;    // Company declined
    #abandoned;   // Driver stopped pursuing
  };

  /// A single advertising pitch tracked in the driver's deal pipeline.
  public type CompanyPitch = {
    id : Text;
    driverId : Text;
    companyName : Text;
    contactPerson : ?Text;
    contactEmail : ?Text;
    contactPhone : ?Text;
    pitchDate : Nat64;
    status : PitchStatus;
    expectedValue : ?Nat;    // Expected R value (in Rands) if the deal closes
    notes : ?Text;
    lastFollowUp : ?Nat64;
    createdAt : Nat64;
    updatedAt : Nat64;
  };

  /// Aggregate stats for a driver's recommendation outcomes in a given month.
  public type OutcomeStats = {
    totalRecommendations : Nat;
    triedCount : Nat;
    skippedCount : Nat;
    partialCount : Nat;
    surgeAccuracy : Float;           // tried / total surge recommendations (0.0–1.0)
    totalRevenueTracked : Nat;       // sum of revenue in cents
    avgRevenuePerTried : Nat;        // avg revenue in cents for tried outcomes
  };

  /// Monthly learning insights generated by the analysis engine.
  public type MonthlyInsights = {
    driverId : Text;
    year : Nat;
    month : Nat;
    surgeAccuracy : Float;
    topSurgeRecommendations : [Text];    // content of tried+successful surge outcomes
    productConversions : [Text];          // content of tried product outcomes
    advertisingStats : {
      pitchesSent : Nat;
      companiesInterested : [Text];
      dealsNegotiating : [Text];
      dealsClosed : [Text];              // company names of closed deals
    };
    suggestedSystemPromptUpdate : Text;  // auto-generated improvement instructions for Nduna
  };
};
