/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AbTestResult {
  'bConversionRate' : number,
  'aConversionRate' : number,
  'campaignAId' : string,
  'campaignBId' : string,
  'decidedAt' : [] | [bigint],
  'winnerCampaignId' : [] | [string],
}
export interface AgentMailConfig {
  'leadFollowupEmailEnabled' : boolean,
  'ndunaInboxId' : [] | [string],
  'apiKey' : string,
  'onboardingEmailEnabled' : boolean,
  'weeklyBriefingEmailEnabled' : boolean,
}
export interface AnalyticsEvent {
  'id' : string,
  'driverId' : string,
  'action' : string,
  'metadata' : string,
  'errorMessage' : [] | [string],
  'tier' : [] | [string],
  'timestamp' : bigint,
  'category' : string,
  'success' : boolean,
  'durationMs' : [] | [bigint],
}
export interface AnalyticsSummary {
  'totalEvents' : bigint,
  'ndunaQueryCount' : bigint,
  'avgNdunaDurationMs' : [] | [bigint],
  'errorCount' : bigint,
  'topActions' : Array<[string, bigint]>,
}
export interface BrandingConfig {
  'accentColor' : string,
  'callToAction' : string,
  'driverName' : string,
  'showMoneyDriveLogo' : boolean,
  'musicPreference' : string,
}
export interface BrowserbaseCompanyResult {
  'keyServices' : Array<string>,
  'source' : string,
  'websiteUrl' : string,
  'hiringSignals' : boolean,
  'estimatedEmployees' : string,
  'description' : string,
  'contactEmail' : [] | [string],
  'companyName' : string,
  'scrapedAt' : bigint,
  'industry' : string,
}
export interface Campaign {
  'id' : string,
  'status' : CampaignStatus,
  'trackingUtm' : string,
  'abWinner' : [] | [boolean],
  'angle' : MessageAngle,
  'creative' : [] | [CampaignCreative],
  'approvedAt' : [] | [bigint],
  'createdAt' : bigint,
  'rejectionReason' : [] | [string],
  'publishedAt' : [] | [bigint],
  'abVariantId' : [] | [string],
  'segment' : DriverSegment,
  'isAbTest' : boolean,
  'channel' : CampaignChannel,
  'adminNotes' : [] | [string],
}
export type CampaignChannel = { 'both' : null } |
  { 'whatsapp' : null } |
  { 'email' : null };
export interface CampaignConfig {
  'maxActiveCampaignsPerDay' : bigint,
  'maxMessagesPerSegmentPerWeek' : bigint,
  'enabled' : boolean,
  'weeklyReportEnabled' : boolean,
  'adminEmail' : string,
}
export interface CampaignCreative {
  'videoJobId' : [] | [string],
  'imageUrl' : string,
  'copySubjectLine' : string,
  'copyBody' : string,
  'copyHook' : string,
  'videoUrl' : [] | [string],
}
export interface CampaignFailureLog {
  'angle' : MessageAngle,
  'campaignId' : string,
  'segment' : DriverSegment,
  'loggedAt' : bigint,
  'reason' : string,
}
export interface CampaignMetrics {
  'lastUpdated' : bigint,
  'campaignId' : string,
  'sends' : bigint,
  'conversionRate' : number,
  'revenueAttributed' : number,
  'paidConversions' : bigint,
  'trialStarts' : bigint,
}
export type CampaignStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'pending_approval' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'draft' : null } |
  { 'archived' : null } |
  { 'paused' : null };
export interface CityLeaderEntry {
  'month' : string,
  'dealsClosed' : bigint,
  'city' : string,
  'topCompany' : string,
  'avgDealValue' : bigint,
}
export type ClipStatus = { 'pending' : null } |
  { 'captioning' : null } |
  { 'branding' : null } |
  { 'ready' : null } |
  { 'failed' : null };
export interface CompanyPitch {
  'id' : string,
  'status' : PitchStatus,
  'driverId' : string,
  'pitchDate' : bigint,
  'expectedValue' : [] | [bigint],
  'createdAt' : bigint,
  'contactPerson' : [] | [string],
  'updatedAt' : bigint,
  'notes' : [] | [string],
  'contactEmail' : [] | [string],
  'companyName' : string,
  'lastFollowUp' : [] | [bigint],
  'contactPhone' : [] | [string],
}
export interface CompanyResponsiveness {
  'companyName' : string,
  'successfulDeals' : bigint,
  'responseRate' : bigint,
  'totalPitches' : bigint,
  'avgDealValue' : bigint,
}
export interface CompanyScore {
  'matchScore' : number,
  'companyName' : string,
  'priority' : bigint,
  'estimatedDealValue' : bigint,
  'reason' : string,
}
export interface CompetitiveStats {
  'month' : string,
  'cityLeaderboard' : Array<CityLeaderEntry>,
  'totalDriversInNetwork' : bigint,
  'topCompanies' : Array<CompanyResponsiveness>,
  'networkSurgeAccuracy' : number,
}
export type ConfidenceLevel = { 'LOW' : null } |
  { 'HIGH' : null } |
  { 'MEDIUM' : null };
export type ConversationChannel = { 'app' : null } |
  { 'whatsapp' : null } |
  { 'telegram' : null };
export interface DocumentRecord {
  'id' : string,
  'driverId' : string,
  'deleted' : boolean,
  'fileName' : string,
  'notes' : string,
  'storageRef' : string,
  'markdownStatus' : [] | [MarkdownStatus],
  'docType' : DocumentType,
  'uploadedAt' : bigint,
  'markdownContent' : [] | [string],
}
export type DocumentType = { 'other' : null } |
  { 'invoice' : null } |
  { 'registration' : null } |
  { 'licence' : null };
export type DriverAction = { 'tried' : null } |
  { 'skipped' : null } |
  { 'partial' : null };
export interface DriverAnalyticsProfile {
  'totalTrips' : bigint,
  'totalKmsDriven' : number,
  'lastCalculated' : bigint,
  'totalExpenses' : number,
  'peakHourRanges' : Array<string>,
  'totalEarnings' : number,
  'totalFuelCost' : number,
  'estimatedCarExposure' : bigint,
  'topEarningDays' : Array<string>,
  'avgEarningsPerHour' : number,
}
export type DriverCohort = { 'NewDriver' : null } |
  { 'PowerEarner' : null } |
  { 'GrowthDriver' : null };
export interface DriverCohortProfile {
  'cohortAdvice' : string,
  'tripsThisMonth' : bigint,
  'earningsThisMonth' : number,
  'upgradeRecommendation' : string,
  'rating' : number,
  'cohort' : DriverCohort,
}
export interface DriverCompetitiveProfile {
  'driverId' : string,
  'surgeAccuracy' : number,
  'city' : string,
  'totalInCity' : bigint,
  'rank' : bigint,
  'dealsClosedCount' : bigint,
  'avgDealValue' : bigint,
}
export interface DriverMemory {
  'lastUpdated' : bigint,
  'userProfile' : string,
  'agentNotes' : string,
}
export interface DriverMemoryEntry {
  'key' : string,
  'value' : string,
  'timestamp' : bigint,
  'category' : string,
}
export interface DriverPaymentConfig {
  'usdtAddress' : string,
  'ethAddress' : string,
  'bankAccount' : string,
  'usdcAddress' : string,
  'bankReference' : string,
  'solAddress' : string,
  'bankName' : string,
  'bnbAddress' : string,
  'btcAddress' : string,
  'snapScanMerchantId' : [] | [string],
  'baseAddress' : string,
}
export interface DriverSegment {
  'city' : string,
  'tier' : bigint,
  'platform' : string,
  'archetype' : string,
  'estimatedCount' : bigint,
}
export interface EarningsGoal { 'period' : string, 'targetAmount' : number }
export interface EmailLog {
  'id' : string,
  'status' : string,
  'driverId' : string,
  'subject' : string,
  'recipient' : string,
  'sentAt' : bigint,
  'emailType' : string,
  'errorMsg' : [] | [string],
}
export interface Event {
  'eventId' : string,
  'title' : string,
  'date' : bigint,
  'description' : string,
  'category' : string,
  'isUserCreated' : boolean,
  'location' : string,
}
export interface EventIntelligence {
  'date' : string,
  'expectedAttendance' : string,
  'name' : string,
  'sourceUrl' : string,
  'driverOpportunityScore' : bigint,
}
export interface ExaCompanyResult {
  'url' : string,
  'employeeCount' : [] | [string],
  'name' : string,
  'description' : [] | [string],
  'snippet' : string,
  'founded' : [] | [string],
  'contactEmail' : [] | [string],
  'industry' : [] | [string],
}
export interface ExpenseEntry {
  'expenseId' : string,
  'date' : bigint,
  'notes' : string,
  'category' : string,
  'amount' : number,
}
export interface ExposureFactor {
  'weight' : number,
  'name' : string,
  'reason' : string,
}
export interface ExposureMetrics {
  'confidenceScore' : number,
  'routeName' : string,
  'factors' : Array<ExposureFactor>,
  'dailyPedestrians' : bigint,
  'monthlyExposure' : bigint,
  'dailyVehicles' : bigint,
}
export interface FetchedEvent {
  'id' : string,
  'title' : string,
  'fetchedAt' : bigint,
  'venue' : string,
  'city' : string,
  'date' : string,
  'driverRelevance' : string,
  'category' : string,
  'isNew' : boolean,
}
export interface FleetExpenseEntry {
  'expenseId' : string,
  'date' : bigint,
  'notes' : string,
  'category' : string,
  'amount' : number,
  'vehicleId' : string,
}
export interface FleetIncomeEntry {
  'incomeId' : string,
  'date' : bigint,
  'platform' : string,
  'notes' : string,
  'amount' : number,
  'vehicleId' : string,
}
export interface FleetVehicle {
  'model' : string,
  'make' : string,
  'color' : [] | [string],
  'year' : [] | [bigint],
  'plateNumber' : string,
  'notes' : [] | [string],
  'vehicleId' : string,
  'dateAdded' : bigint,
}
export interface FleetVehicleSummary {
  'model' : string,
  'expenseCount' : bigint,
  'make' : string,
  'totalIncome' : number,
  'totalExpenses' : number,
  'plateNumber' : string,
  'tripCount' : bigint,
  'vehicleId' : string,
  'netProfit' : number,
}
export type ForumChannel = { 'whatILove' : null } |
  { 'featureRequests' : null } |
  { 'whatNeedsWork' : null };
export interface ForumPage {
  'total' : bigint,
  'nextOffset' : [] | [bigint],
  'posts' : Array<ForumPost>,
}
export interface ForumPost {
  'id' : ForumPostId,
  'deleted' : boolean,
  'likeCount' : bigint,
  'authorId' : UserId,
  'voiceNoteKey' : [] | [string],
  'text' : string,
  'isAnonymous' : boolean,
  'timestamp' : Timestamp,
  'replyCount' : bigint,
  'channel' : ForumChannel,
  'parentId' : [] | [ForumPostId],
  'flagCount' : bigint,
}
export type ForumPostId = string;
export interface FuelLog {
  'cost' : number,
  'date' : bigint,
  'distance' : number,
  'fuelUsed' : number,
}
export interface HyperframesJob {
  'id' : string,
  'driverId' : string,
  'topic' : string,
  'compositionHtml' : string,
  'mp4Url' : [] | [string],
  'createdAt' : bigint,
  'renderStatus' : HyperframesRenderStatus,
  'errorMsg' : [] | [string],
}
export type HyperframesRenderStatus = { 'pending' : null } |
  { 'rendering' : null } |
  { 'ready' : null } |
  { 'failed' : null };
export type IntelligenceCategory = { 'surgeWindows' : null } |
  { 'adConversionRates' : null } |
  { 'leadQuality' : null } |
  { 'earningsBenchmarks' : null } |
  { 'topZones' : null };
export interface IntelligenceDataPoint {
  'value' : number,
  'name' : string,
  'unit' : string,
  'sampleSize' : bigint,
}
export interface IntelligenceQuery {
  'city' : [] | [string],
  'limit' : bigint,
  'category' : IntelligenceCategory,
}
export interface IntelligenceResult {
  'city' : string,
  'data' : Array<IntelligenceDataPoint>,
  'generatedAt' : bigint,
  'category' : string,
}
export interface LatencyPercentiles {
  'p50' : bigint,
  'p95' : bigint,
  'p99' : bigint,
}
export interface LeadBatch {
  'driverId' : string,
  'generatedAt' : bigint,
  'year' : bigint,
  'weekNumber' : bigint,
  'leads' : Array<ScrapedLead>,
  'totalRanked' : bigint,
  'totalScraped' : bigint,
}
export type LeadStatus = { 'pending' : null } |
  { 'pitched' : null } |
  { 'rejected' : null } |
  { 'dealClosed' : null } |
  { 'interested' : null };
export type MarkdownStatus = { 'pending' : null } |
  { 'unsupported' : null } |
  { 'converting' : null } |
  { 'ready' : null } |
  { 'failed' : null };
export type MessageAngle = { 'limited_time_offer' : null } |
  { 'feature_benefit' : null } |
  { 'referral_incentive' : null } |
  { 'earnings_proof' : null };
export type MessageDeliveryStatus = { 'read' : null } |
  { 'sent' : null } |
  { 'delivered' : null } |
  { 'failed' : null };
export type MessageDirection = { 'inbound' : null } |
  { 'outbound' : null };
export interface MetricEntry {
  'model' : string,
  'wasCached' : boolean,
  'error' : [] | [string],
  'isGateway' : boolean,
  'timestamp' : bigint,
  'durationMs' : bigint,
}
export interface MonthlyInsights {
  'suggestedSystemPromptUpdate' : string,
  'driverId' : string,
  'month' : bigint,
  'topSurgeRecommendations' : Array<string>,
  'surgeAccuracy' : number,
  'productConversions' : Array<string>,
  'year' : bigint,
  'advertisingStats' : {
    'dealsNegotiating' : Array<string>,
    'companiesInterested' : Array<string>,
    'dealsClosed' : Array<string>,
    'pitchesSent' : bigint,
  },
}
export interface NdunaEmail {
  'messageId' : string,
  'subject' : string,
  'preview' : string,
  'from' : string,
  'isRead' : boolean,
  'receivedAt' : bigint,
  'inboxId' : string,
}
export interface NdunaRecommendation {
  'driverId' : string,
  'content' : string,
  'recommendationType' : string,
  'timestamp' : bigint,
  'confidence' : string,
}
export interface NdunaRecommendationV2 {
  'id' : string,
  'driverId' : string,
  'content' : string,
  'recommendationType' : RecommendationType,
  'timestamp' : bigint,
  'confidence' : ConfidenceLevel,
}
export interface NdunaSystemPromptState {
  'evolutionDelta' : string,
  'lastEvolved' : [] | [bigint],
  'basePrompt' : string,
  'evolutionCount' : bigint,
}
export type OpportunityCategory = { 'businessLead' : null } |
  { 'newPlatform' : null } |
  { 'incomeCategory' : null } |
  { 'platformPromotion' : null } |
  { 'intercityRoute' : null } |
  { 'regulatoryChange' : null };
export interface OpportunityFinding {
  'id' : string,
  'driverId' : string,
  'title' : string,
  'expiresAt' : bigint,
  'source' : string,
  'description' : string,
  'relevanceScore' : bigint,
  'category' : OpportunityCategory,
  'discoveredAt' : bigint,
  'dismissed' : boolean,
}
export interface OrbisListingConfig {
  'providerApiKey' : string,
  'pricePerCall' : number,
  'listingName' : string,
  'autoPublish' : boolean,
}
export interface OrbisListingStatus {
  'listingId' : [] | [string],
  'totalCalls' : bigint,
  'usdcEarned' : number,
  'listed' : boolean,
}
export interface OrderItem {
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : number,
}
export interface OutcomeStats {
  'partialCount' : bigint,
  'avgRevenuePerTried' : bigint,
  'surgeAccuracy' : number,
  'totalRecommendations' : bigint,
  'triedCount' : bigint,
  'skippedCount' : bigint,
  'totalRevenueTracked' : bigint,
}
export interface PassengerOrder {
  'paymentMethod' : string,
  'orderId' : string,
  'passengerNote' : string,
  'totalAmount' : number,
  'timestamp' : bigint,
  'items' : Array<OrderItem>,
  'driverName' : string,
}
export type PitchStatus = { 'closed' : null } |
  { 'sent' : null } |
  { 'abandoned' : null } |
  { 'rejected' : null } |
  { 'interested' : null } |
  { 'negotiating' : null } |
  { 'viewed' : null };
export type PostStatus = { 'scheduled' : null } |
  { 'failed' : null } |
  { 'posted' : null };
export interface PostingSchedule {
  'driverId' : string,
  'preferredHourUtc' : bigint,
  'enabled' : boolean,
  'postsPerWeek' : bigint,
  'preferredDays' : Array<bigint>,
  'platformsEnabled' : Array<SocialPlatform>,
}
export interface PresentationData {
  'id' : string,
  'generatedAt' : bigint,
  'shareToken' : string,
  'slides' : Array<Slide>,
}
export interface PresentationInput {
  'targetIndustry' : string,
  'tripsPerMonth' : bigint,
  'estimatedMonthlyExposure' : bigint,
  'city' : string,
  'targetCompanyName' : string,
  'vehicleModel' : string,
  'routes' : string,
  'proposedDealValue' : bigint,
  'driverName' : string,
  'avgPassengers' : bigint,
}
export interface ProactiveTrigger {
  'page' : string,
  'triggerType' : string,
  'message' : string,
}
export interface Product {
  'name' : string,
  'sellingPrice' : number,
  'productId' : string,
  'currentStock' : bigint,
}
export interface RecommendationOutcome {
  'revenue' : [] | [bigint],
  'driverAction' : [] | [string],
  'recommendationId' : bigint,
  'timestamp' : bigint,
  'outcome' : [] | [string],
}
export interface RecommendationOutcomeV2 {
  'driverId' : string,
  'action' : DriverAction,
  'revenue' : [] | [bigint],
  'recordedAt' : bigint,
  'recommendationId' : string,
  'notes' : [] | [string],
}
export type RecommendationType = { 'advertising' : null } |
  { 'surge' : null } |
  { 'product' : null };
export interface ReferralCode {
  'ownerName' : string,
  'ownerId' : string,
  'code' : string,
  'createdAt' : bigint,
  'totalEarned' : number,
  'timesUsed' : bigint,
}
export interface ReferralConfig {
  'bonusDescription' : string,
  'minTripsToQualify' : bigint,
  'enabled' : boolean,
  'bonusSource' : string,
  'bonusPerReferral' : number,
}
export interface ReferralUse {
  'referredUserId' : string,
  'bonusAmount' : number,
  'code' : string,
  'usedAt' : bigint,
  'bonusPaid' : boolean,
}
export type Result = { 'ok' : { 'url' : string, 'claimUrl' : string } } |
  { 'err' : string };
export type Result_1 = { 'ok' : WebsiteJob } |
  { 'err' : string };
export interface RouteOptIn {
  'driverId' : string,
  'secondaryRoute' : [] | [SAZone],
  'optedInAt' : bigint,
  'primaryRoute' : SAZone,
}
export type SAZone = { 'JohannesburgCBD' : null } |
  { 'CapeTownCBD' : null } |
  { 'PretoriaCBD' : null } |
  { 'Midrand' : null } |
  { 'Soweto' : null } |
  { 'Generic' : null } |
  { 'Umhlanga' : null } |
  { 'DurbanBeachfront' : null } |
  { 'Sandton' : null };
export interface Sale {
  'saleId' : string,
  'date' : bigint,
  'productName' : string,
  'totalAmount' : number,
  'quantity' : bigint,
}
export interface SchedulerConfig {
  'dayOfWeek' : bigint,
  'hour' : bigint,
  'enabled' : boolean,
}
export interface ScrapedLead {
  'id' : string,
  'status' : LeadStatus,
  'tavilySnippet' : string,
  'driverId' : string,
  'source' : string,
  'scoringFactors' : string,
  'year' : bigint,
  'weekNumber' : bigint,
  'email' : string,
  'website' : string,
  'browserbaseEnriched' : [] | [BrowserbaseCompanyResult],
  'exaEnriched' : [] | [ExaCompanyResult],
  'address' : string,
  'companyName' : string,
  'tavilyHiringSignal' : boolean,
  'phone' : string,
  'compositeScore' : bigint,
  'scrapedAt' : bigint,
  'industry' : string,
}
export interface ScraperAuditLog {
  'id' : string,
  'url' : string,
  'driverId' : string,
  'source' : string,
  'errorMessage' : [] | [string],
  'timestamp' : bigint,
  'success' : boolean,
  'companiesFound' : bigint,
}
export interface Shift {
  'startTime' : string,
  'status' : string,
  'endTime' : string,
  'date' : bigint,
  'targetEarnings' : number,
  'notes' : string,
  'shiftId' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface ShortsConfig {
  'vpsKey' : [] | [string],
  'vpsUrl' : [] | [string],
}
export interface ShortsJob {
  'id' : string,
  'driverId' : Principal,
  'selectedSegmentEnd' : [] | [bigint],
  'outputMp4Url' : [] | [string],
  'clipStatus' : ShortsStatus,
  'selectedSegmentStart' : [] | [bigint],
  'createdAt' : bigint,
  'sourceUrl' : string,
  'sourceType' : { 'upload' : null } |
    { 'youtube' : null },
  'errorMsg' : [] | [string],
}
export interface ShortsRequest {
  'sourceUrl' : string,
  'sourceType' : { 'upload' : null } |
    { 'youtube' : null },
}
export type ShortsStatus = { 'pending' : null } |
  { 'selecting' : null } |
  { 'transcribing' : null } |
  { 'rendering' : null } |
  { 'ready' : null } |
  { 'failed' : null };
export interface Slide {
  'dataPoint' : [] | [string],
  'title' : string,
  'bullets' : Array<string>,
  'slideType' : string,
  'speakerNotes' : string,
}
export interface SmartRecommendation {
  'dataPoint' : string,
  'urgency' : string,
  'score' : CompanyScore,
  'companyName' : string,
  'pitch' : string,
}
export type SocialPlatform = { 'linkedin' : null } |
  { 'tiktok' : null } |
  { 'instagram' : null } |
  { 'youtube' : null };
export interface StakingRecord {
  'stakeId' : string,
  'dissolveDelayDays' : bigint,
  'notes' : string,
  'icpAmount' : number,
  'startDate' : bigint,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Summary {
  'cacheHits' : bigint,
  'gatewayRequests' : bigint,
  'directRequests' : bigint,
  'avgDirectMs' : bigint,
  'errorCount' : bigint,
  'avgGatewayMs' : bigint,
  'totalRequests' : bigint,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface Trip {
  'date' : bigint,
  'tripId' : string,
  'platform' : string,
  'durationMinutes' : bigint,
  'notes' : string,
  'amount' : number,
}
export interface UploadPostConfig { 'accountId' : string, 'apiKey' : string }
export type UploadStatus = { 'pending' : null } |
  { 'processing' : null } |
  { 'ready' : null } |
  { 'failed' : null };
export type UserId = Principal;
export interface UserProfile {
  'vehicleName' : string,
  'displayName' : string,
  'subscriptionTier' : bigint,
  'voiceEnabled' : boolean,
  'currencyCode' : string,
  'fuelConsumptionRate' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoAnalytics {
  'shares' : bigint,
  'fetchedAt' : bigint,
  'views' : bigint,
  'engagementRate' : number,
  'platform' : SocialPlatform,
  'likes' : bigint,
  'comments' : bigint,
  'postId' : string,
}
export interface VideoClip {
  'id' : string,
  'driverId' : string,
  'brandedStorageRef' : [] | [string],
  'title' : [] | [string],
  'processingStatus' : ClipStatus,
  'startSec' : number,
  'storageRef' : string,
  'uploadId' : string,
  'durationSec' : number,
  'errorMsg' : [] | [string],
  'captionsVttRef' : [] | [string],
  'endSec' : number,
}
export interface VideoJobStatus {
  'clipsFailed' : bigint,
  'postsPosted' : bigint,
  'postsScheduled' : bigint,
  'clipsReady' : bigint,
  'lastUpdatedAt' : bigint,
  'clipsGenerated' : bigint,
  'uploadId' : string,
}
export interface VideoPost {
  'id' : string,
  'status' : PostStatus,
  'clipId' : string,
  'driverId' : string,
  'postedAt' : [] | [bigint],
  'platformPostId' : [] | [string],
  'platform' : SocialPlatform,
  'errorMsg' : [] | [string],
  'scheduledAt' : [] | [bigint],
}
export interface VideoUpload {
  'id' : string,
  'driverId' : string,
  'processingStatus' : UploadStatus,
  'contentType' : string,
  'fileSizeBytes' : bigint,
  'fileName' : string,
  'storageRef' : string,
  'errorMsg' : [] | [string],
  'uploadedAt' : bigint,
}
export interface VoiceUsage { 'date' : bigint, 'count' : bigint }
export interface WebsiteJob {
  'id' : string,
  'status' : WebsiteJobStatus,
  'driverId' : string,
  'topic' : string,
  'shareUrl' : [] | [string],
  'createdAt' : bigint,
  'htmlContent' : [] | [string],
  'updatedAt' : bigint,
  'iteration' : bigint,
  'errorMsg' : [] | [string],
}
export type WebsiteJobStatus = { 'pending' : null } |
  { 'generating' : null } |
  { 'ready' : null } |
  { 'failed' : null };
export interface WeeklyBriefingState {
  'briefingDayOfWeek' : bigint,
  'lastSentAt' : [] | [bigint],
  'enabled' : boolean,
  'briefingHour' : bigint,
}
export interface WeeklyReport {
  'activeCampaigns' : Array<string>,
  'worstAngle' : [] | [string],
  'totalTrialStarts' : bigint,
  'topAngle' : [] | [string],
  'totalSends' : bigint,
  'revenueAttributed' : number,
  'totalConversions' : bigint,
  'weekOf' : string,
}
export interface WhatsAppConfig {
  'webhookSecret' : string,
  'apiKey' : string,
  'phoneNumber' : string,
}
export interface WhatsAppConversationEntry {
  'driverId' : string,
  'direction' : MessageDirection,
  'messageId' : string,
  'body' : string,
  'deliveryStatus' : MessageDeliveryStatus,
  'timestamp' : bigint,
  'channel' : ConversationChannel,
  'errorMsg' : [] | [string],
  'mediaStorageRef' : [] | [string],
}
export interface WhisperConfig { 'model' : string, 'apiKey' : string }
export interface WhisperConfig__1 { 'apiKey' : string }
export interface XPost {
  'id' : bigint,
  'status' : XPostStatus,
  'postType' : XPostType,
  'postedAt' : [] | [bigint],
  'content' : string,
  'retweetsCount' : bigint,
  'impressionsCount' : bigint,
  'xPostId' : [] | [string],
  'likesCount' : bigint,
  'repliesCount' : bigint,
}
export type XPostStatus = { 'scheduled' : null } |
  { 'pending' : null } |
  { 'failed' : null } |
  { 'posted' : null };
export type XPostType = { 'DriverWin' : null } |
  { 'IncomeTip' : null } |
  { 'TaskOutcome' : null } |
  { 'SAIntelligence' : null };
export interface XPostingConfig {
  'xAccessTokenSecret' : string,
  'monthlyEarningsCents' : bigint,
  'totalPostsPublished' : bigint,
  'xApiKey' : string,
  'earningsThresholdUsd' : bigint,
  'xAccessToken' : string,
  'xApiSecret' : string,
  'lastPostAt' : [] | [bigint],
  'isUnlocked' : boolean,
}
export interface ZeroXWorkEarnings {
  'tasksCompleted' : bigint,
  'totalUSDCEarned' : number,
}
export interface ZeroXWorkStatus {
  'tasksCompleted' : bigint,
  'walletAddress' : string,
  'activeTaskId' : [] | [string],
  'registered' : boolean,
}
export interface ZeroXWorkTask {
  'reward' : number,
  'title' : string,
  'description' : string,
  'taskId' : string,
  'capability' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCustomEvent' : ActorMethod<[Event], undefined>,
  'addDocumentNote' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'addDriverMemoryEntry' : ActorMethod<
    [DriverMemoryEntry],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addExpense' : ActorMethod<[ExpenseEntry], undefined>,
  'addFleetExpense' : ActorMethod<
    [string, string, number, bigint, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addFleetIncome' : ActorMethod<
    [string, string, number, bigint, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addFleetVehicle' : ActorMethod<
    [string, string, string, [] | [bigint], [] | [string], [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addFuelLog' : ActorMethod<[FuelLog], undefined>,
  'addOrUpdateProduct' : ActorMethod<[Product], undefined>,
  'addOrUpdateShift' : ActorMethod<[Shift], undefined>,
  'addSale' : ActorMethod<[Sale], undefined>,
  'addTrip' : ActorMethod<[Trip], undefined>,
  'adminListAllDocuments' : ActorMethod<[], Array<DocumentRecord>>,
  'applyReferralCode' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'applyReferralCreditToPayment' : ActorMethod<
    [number],
    {
      'remainingBalance' : number,
      'amountDue' : number,
      'creditApplied' : number,
    }
  >,
  'approveCampaign' : ActorMethod<
    [string, [] | [bigint]],
    { 'ok' : Campaign } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buildAdvertisingBusinessCase' : ActorMethod<[], string>,
  'checkAbTestResults' : ActorMethod<[], Array<AbTestResult>>,
  'claimZeroXWorkTask' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin only: clear (disable) the Cloudflare AI Gateway — reverts to direct calls.
   */
  'clearAIGatewayConfig' : ActorMethod<[], undefined>,
  'clearAgentConversation' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createForumPost' : ActorMethod<
    [ForumChannel, string, boolean, [] | [string], [] | [ForumPostId]],
    { 'ok' : ForumPost } |
      { 'err' : string }
  >,
  'createOrUpdateProfile' : ActorMethod<[UserProfile], undefined>,
  'createPitch' : ActorMethod<[CompanyPitch], string>,
  'createVideoPost' : ActorMethod<
    [string, SocialPlatform, [] | [bigint]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createVideoUpload' : ActorMethod<
    [string, string, bigint, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteCustomEvent' : ActorMethod<[string], undefined>,
  'deleteDocument' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteExpense' : ActorMethod<[string], undefined>,
  'deleteFleetExpense' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteFleetIncome' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteFleetVehicle' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteForumPost' : ActorMethod<
    [ForumPostId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deletePassengerOrder' : ActorMethod<[string], undefined>,
  'deletePitch' : ActorMethod<[string], boolean>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteSale' : ActorMethod<[string], undefined>,
  'deleteShift' : ActorMethod<[string], undefined>,
  'deleteStakingRecord' : ActorMethod<[string], undefined>,
  'deleteTrip' : ActorMethod<[string], undefined>,
  'detectSurgeOpportunities' : ActorMethod<[], string>,
  'dismissOpportunity' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'elevenLabsTextToSpeech' : ActorMethod<[string], Uint8Array>,
  'fetchAndStoreAnalytics' : ActorMethod<[], undefined>,
  'fetchAndStoreSAEvents' : ActorMethod<
    [boolean],
    { 'ok' : Array<FetchedEvent> } |
      { 'err' : string }
  >,
  'flagForumPost' : ActorMethod<
    [ForumPostId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'generateDriverWebsite' : ActorMethod<[string], Result_1>,
  'generateFollowUpReminders' : ActorMethod<[string], Array<string>>,
  'generateHyperframesSlideshow' : ActorMethod<
    [string],
    { 'ok' : HyperframesJob } |
      { 'err' : string }
  >,
  'generatePresentation' : ActorMethod<
    [PresentationInput],
    { 'ok' : PresentationData } |
      { 'err' : string }
  >,
  'generateSystemPromptDelta' : ActorMethod<[MonthlyInsights], string>,
  'generateWeeklyReport' : ActorMethod<[], WeeklyReport>,
  'get0xWorkEarnings' : ActorMethod<[], ZeroXWorkEarnings>,
  'get0xWorkStatus' : ActorMethod<[], ZeroXWorkStatus>,
  /**
   * / Returns gateway configuration status. Never returns the API key.
   */
  'getAIGatewayStatus' : ActorMethod<
    [],
    { 'url' : [] | [string], 'configured' : boolean }
  >,
  'getAllReferrals' : ActorMethod<[], Array<ReferralUse>>,
  /**
   * / Admin only: returns aggregated analytics summary.
   */
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  /**
   * / Admin only: returns true if Brian API key is configured and non-empty.
   */
  'getBrianApiKeyStatus' : ActorMethod<[], boolean>,
  /**
   * / Admin only: returns true if CMC API key is configured and non-empty.
   */
  'getCMCApiKeyStatus' : ActorMethod<[], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaignConfig' : ActorMethod<[], CampaignConfig>,
  'getCampaignFailureLog' : ActorMethod<[], Array<CampaignFailureLog>>,
  'getCampaignMetrics' : ActorMethod<
    [string],
    { 'ok' : CampaignMetrics } |
      { 'err' : string }
  >,
  'getCohortStats' : ActorMethod<
    [],
    { 'powerEarners' : bigint, 'growthDrivers' : bigint, 'newDrivers' : bigint }
  >,
  'getCompetitiveStats' : ActorMethod<[], CompetitiveStats>,
  'getContextSummary' : ActorMethod<[], string>,
  'getCustomEvents' : ActorMethod<[], Array<Event>>,
  'getDocVaultConfig' : ActorMethod<[], { 'notesEnabled' : boolean }>,
  'getDocumentMarkdown' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Caller sees their own events; admin can pass any driverId.
   * / Limit is capped at 100 to avoid large responses.
   */
  'getDriverAnalyticsEvents' : ActorMethod<
    [string, bigint],
    Array<AnalyticsEvent>
  >,
  'getDriverAnalyticsProfile' : ActorMethod<[], [] | [DriverAnalyticsProfile]>,
  'getDriverCohortProfile' : ActorMethod<[], DriverCohortProfile>,
  'getDriverCreditBalance' : ActorMethod<[string], number>,
  'getDriverEarningsSnapshot' : ActorMethod<[], string>,
  'getDriverLeadBatch' : ActorMethod<[bigint, bigint], [] | [LeadBatch]>,
  'getDriverLeads' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<ScrapedLead>
  >,
  'getDriverMemory' : ActorMethod<[], [] | [DriverMemory]>,
  'getDriverMemoryEntries' : ActorMethod<[], Array<DriverMemoryEntry>>,
  'getDriverOpportunities' : ActorMethod<[bigint], Array<OpportunityFinding>>,
  'getDriverOutcomesV2' : ActorMethod<[string], Array<RecommendationOutcomeV2>>,
  'getDriverPitches' : ActorMethod<[string], Array<CompanyPitch>>,
  'getDriverProfileSummary' : ActorMethod<[], string>,
  'getDriverRating' : ActorMethod<[], number>,
  'getEarningsGoal' : ActorMethod<[], [] | [EarningsGoal]>,
  'getEarningsTotal' : ActorMethod<[], [number, bigint]>,
  'getElevenLabsSignedUrl' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getEmailConfig' : ActorMethod<[], AgentMailConfig>,
  'getEmailLogs' : ActorMethod<[], Array<EmailLog>>,
  /**
   * / Admin only: returns the last `limit` error events (success=false).
   */
  'getErrorLog' : ActorMethod<[bigint], Array<AnalyticsEvent>>,
  'getEventRelevanceScore' : ActorMethod<[string, bigint], string>,
  'getEventsWithTavilyIntelligence' : ActorMethod<
    [string],
    { 'ok' : Array<EventIntelligence> } |
      { 'err' : string }
  >,
  /**
   * / Admin only: returns a masked preview of the Exa API key.
   * / Shows first 6 characters followed by "***", or "***" if short/empty.
   */
  'getExaApiKey' : ActorMethod<[], string>,
  'getExpenses' : ActorMethod<[], Array<ExpenseEntry>>,
  'getExposureMetrics' : ActorMethod<[SAZone], ExposureMetrics>,
  'getExposureMetricsWithTrips' : ActorMethod<
    [SAZone, bigint],
    ExposureMetrics
  >,
  'getFetchedEvents' : ActorMethod<[], Array<FetchedEvent>>,
  'getFleetExpenses' : ActorMethod<[[] | [string]], Array<FleetExpenseEntry>>,
  'getFleetIncome' : ActorMethod<[[] | [string]], Array<FleetIncomeEntry>>,
  'getFleetSummary' : ActorMethod<[], Array<FleetVehicleSummary>>,
  'getFleetVehicles' : ActorMethod<[], Array<FleetVehicle>>,
  'getForumAdminStats' : ActorMethod<
    [],
    {
      'flaggedPosts' : Array<ForumPost>,
      'topContributors' : Array<[string, bigint]>,
      'totalPosts' : bigint,
      'postsPerChannel' : Array<[string, bigint]>,
    }
  >,
  'getForumPost' : ActorMethod<[ForumPostId], [] | [ForumPost]>,
  'getForumPosts' : ActorMethod<[ForumChannel, bigint, bigint], ForumPage>,
  'getForumReplies' : ActorMethod<[ForumPostId, bigint, bigint], ForumPage>,
  'getFuelLogs' : ActorMethod<[], Array<FuelLog>>,
  'getFuelProfile' : ActorMethod<
    [],
    { 'vehicleName' : string, 'fuelConsumptionRate' : number }
  >,
  /**
   * / Admin only: returns current cache hit rate as a percentage (0.0–1.0).
   */
  'getGatewayCacheHitRate' : ActorMethod<[], number>,
  /**
   * / Admin only: returns latency percentiles (p50/p95/p99) from the rolling sample buffer.
   */
  'getGatewayLatencyPercentiles' : ActorMethod<[], LatencyPercentiles>,
  /**
   * / Admin only: returns aggregated gateway metrics summary.
   */
  'getGatewayMetricsSummary' : ActorMethod<[], Summary>,
  /**
   * / Admin only: returns the last `limit` gateway metric entries.
   */
  'getGatewayRecentEntries' : ActorMethod<[bigint], Array<MetricEntry>>,
  /**
   * / Admin only: returns the top 5 busiest hours by request count.
   */
  'getGatewayTopHours' : ActorMethod<[], Array<[string, bigint]>>,
  'getHyperframesConfig' : ActorMethod<[], { 'configured' : boolean }>,
  'getHyperframesJob' : ActorMethod<[string], [] | [HyperframesJob]>,
  'getHyperframesJobs' : ActorMethod<[], Array<HyperframesJob>>,
  'getICPPrice' : ActorMethod<[], string>,
  'getLeadAuditLog' : ActorMethod<[], Array<ScraperAuditLog>>,
  'getLowStockProducts' : ActorMethod<[], Array<Product>>,
  'getMonthOutcomes' : ActorMethod<
    [string, bigint, bigint],
    Array<RecommendationOutcomeV2>
  >,
  'getMyCompetitiveProfile' : ActorMethod<[], [] | [DriverCompetitiveProfile]>,
  'getMyPaymentConfig' : ActorMethod<[], [] | [DriverPaymentConfig]>,
  'getMyReferralCode' : ActorMethod<[], ReferralCode>,
  'getMyReferralCredit' : ActorMethod<[], number>,
  'getMyRouteOptIn' : ActorMethod<[], [] | [RouteOptIn]>,
  'getMySnapScanMerchantId' : ActorMethod<[], [] | [string]>,
  'getNdunaInboxId' : ActorMethod<[], [] | [string]>,
  'getNdunaInboxMessages' : ActorMethod<[], Array<NdunaEmail>>,
  'getNdunaPromptState' : ActorMethod<[], NdunaSystemPromptState>,
  'getOpenClawModel' : ActorMethod<[], string>,
  'getOpportunityHunterStatus' : ActorMethod<
    [],
    { 'configured' : boolean, 'lastError' : string, 'lastRun' : bigint }
  >,
  /**
   * / Admin only: returns true if the Orbis API key is configured and non-empty.
   */
  'getOrbisApiKeyStatus' : ActorMethod<[], boolean>,
  'getOrbisPublisherStatus' : ActorMethod<[], OrbisListingStatus>,
  'getOutcomeStats' : ActorMethod<[string, bigint, bigint], OutcomeStats>,
  'getOutcomeV2' : ActorMethod<[string], [] | [RecommendationOutcomeV2]>,
  'getPassengerOrders' : ActorMethod<[], Array<PassengerOrder>>,
  /**
   * / Returns the current pilot mode status. Public query — readable by the frontend.
   */
  'getPilotMode' : ActorMethod<[], boolean>,
  'getPitch' : ActorMethod<[string], [] | [CompanyPitch]>,
  'getPitchesByStatus' : ActorMethod<
    [string, PitchStatus],
    Array<CompanyPitch>
  >,
  'getPostingSchedule' : ActorMethod<[], [] | [PostingSchedule]>,
  'getPresentation' : ActorMethod<[string], [] | [PresentationData]>,
  'getProactiveTriggers' : ActorMethod<[], Array<ProactiveTrigger>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getPublicDriverMenu' : ActorMethod<[string], Array<Product>>,
  'getPublicDriverPaymentConfig' : ActorMethod<
    [string],
    [] | [DriverPaymentConfig]
  >,
  /**
   * / Admin only: returns the last `limit` events across all drivers (newest first).
   */
  'getRecentAnalyticsEvents' : ActorMethod<[bigint], Array<AnalyticsEvent>>,
  'getReferralConfig' : ActorMethod<[], ReferralConfig>,
  'getReferralStats' : ActorMethod<
    [],
    { 'totalEarned' : number, 'pendingBonus' : number, 'timesUsed' : bigint }
  >,
  'getRemainingNdunaQueries' : ActorMethod<[], bigint>,
  'getSAIntelligence' : ActorMethod<
    [IntelligenceQuery],
    { 'ok' : IntelligenceResult } |
      { 'err' : string }
  >,
  'getSales' : ActorMethod<[], Array<Sale>>,
  'getSchedulerConfig' : ActorMethod<[], SchedulerConfig>,
  'getShiftHistory' : ActorMethod<[], Array<Shift>>,
  'getShifts' : ActorMethod<[], Array<Shift>>,
  'getShortsConfig' : ActorMethod<[], ShortsConfig>,
  'getShortsJob' : ActorMethod<[string], [] | [ShortsJob]>,
  'getSmartRecommendations' : ActorMethod<[], Array<SmartRecommendation>>,
  'getSnapScanMerchantId' : ActorMethod<[], string>,
  'getStakingRecords' : ActorMethod<[], Array<StakingRecord>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTavilyUsageEstimate' : ActorMethod<[], bigint>,
  'getTierPricing' : ActorMethod<
    [],
    { 'tier1' : bigint, 'tier2' : bigint, 'tier3' : bigint }
  >,
  'getTrips' : ActorMethod<[], Array<Trip>>,
  /**
   * / Live USDC/ZAR exchange rate from CoinGecko. 10-minute canister cache.
   * / Returns raw JSON: {"usd-coin":{"zar":18.52}} or a plain float string on cache hit.
   */
  'getUSDCZARRate' : ActorMethod<[], string>,
  'getUnreadWhatsAppCount' : ActorMethod<[], bigint>,
  'getUpcomingShifts' : ActorMethod<[], Array<Shift>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoAnalytics' : ActorMethod<[string], Array<VideoAnalytics>>,
  'getVideoBrandingConfig' : ActorMethod<[], [] | [BrandingConfig]>,
  'getVideoClip' : ActorMethod<[string], [] | [VideoClip]>,
  'getVideoClips' : ActorMethod<[string], Array<VideoClip>>,
  'getVideoJobStatus' : ActorMethod<[string], [] | [VideoJobStatus]>,
  'getVideoPosts' : ActorMethod<[string], Array<VideoPost>>,
  'getVideoUpload' : ActorMethod<[string], [] | [VideoUpload]>,
  'getVideoUploads' : ActorMethod<[], Array<VideoUpload>>,
  'getVoiceUsage' : ActorMethod<[], VoiceUsage>,
  'getWebsiteBuilderRateLimit' : ActorMethod<[], bigint>,
  'getWebsiteJob' : ActorMethod<[string], [] | [WebsiteJob]>,
  'getWebsiteJobs' : ActorMethod<[], Array<WebsiteJob>>,
  'getWeeklyBriefingState' : ActorMethod<[], WeeklyBriefingState>,
  'getWhatsAppConfig' : ActorMethod<[], [] | [WhatsAppConfig]>,
  'getWhatsAppHistory' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<WhatsAppConversationEntry>
  >,
  'getXPostingConfig' : ActorMethod<[], XPostingConfig>,
  'getXPostingStatus' : ActorMethod<
    [],
    {
      'earningsCents' : bigint,
      'totalPosts' : bigint,
      'isUnlocked' : boolean,
      'progressPct' : bigint,
      'thresholdCents' : bigint,
    }
  >,
  'getXPosts' : ActorMethod<[bigint, bigint], Array<XPost>>,
  'getZeroXWorkTasks' : ActorMethod<[], Array<ZeroXWorkTask>>,
  'handleSnapScanWebhook' : ActorMethod<[string, string], string>,
  'hasLikedForumPost' : ActorMethod<[ForumPostId], boolean>,
  'incrementVoiceUsage' : ActorMethod<[], bigint>,
  'isBrowserbaseConfigured' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCamofoxConfigured' : ActorMethod<[], boolean>,
  'isElevenLabsConfigured' : ActorMethod<[], boolean>,
  'isOpenClawConfigured' : ActorMethod<[], boolean>,
  'isOpportunityHunterConfigured' : ActorMethod<[], boolean>,
  'isSnapScanConfigured' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isTavilyConfigured' : ActorMethod<[], boolean>,
  'isUploadPostConfigured' : ActorMethod<[], boolean>,
  'isWhatsAppConfigured' : ActorMethod<[], boolean>,
  'isZeroXWorkRegistered' : ActorMethod<[], boolean>,
  'iterateDriverWebsite' : ActorMethod<[string, string], Result_1>,
  'likeForumPost' : ActorMethod<
    [ForumPostId],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'listCampaigns' : ActorMethod<[[] | [CampaignStatus]], Array<Campaign>>,
  'listDriverDocuments' : ActorMethod<[], Array<DocumentRecord>>,
  'listShortsJobs' : ActorMethod<[], Array<ShortsJob>>,
  'logBehavioralEvent' : ActorMethod<
    [string, string, string, bigint],
    undefined
  >,
  'logOutcomeEvent' : ActorMethod<[string, string], undefined>,
  'logPassengerOrder' : ActorMethod<[string, PassengerOrder], undefined>,
  'logRecommendation' : ActorMethod<[NdunaRecommendation], bigint>,
  'logRecommendationV2' : ActorMethod<[NdunaRecommendationV2], string>,
  'markEventsAsRead' : ActorMethod<[], undefined>,
  'monthlyAnalysis' : ActorMethod<[string, bigint, bigint], MonthlyInsights>,
  'monthlyPromptEvolution' : ActorMethod<[], string>,
  'pauseAllCampaigns' : ActorMethod<[], boolean>,
  'proposeCampaign' : ActorMethod<[], { 'ok' : Campaign } | { 'err' : string }>,
  'provisionNdunaInbox' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'publishDriverWebsite' : ActorMethod<[string], Result>,
  'queryAIAgent' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'queryDocumentsByType' : ActorMethod<[string], Array<DocumentRecord>>,
  'recalculateDriverProfile' : ActorMethod<[], DriverAnalyticsProfile>,
  'receiveWhatsAppWebhook' : ActorMethod<[string, string], string>,
  'recordConversion' : ActorMethod<[string, string, string], boolean>,
  'recordExposureOutcome' : ActorMethod<[bigint, bigint], undefined>,
  'recordOutcome' : ActorMethod<[bigint, RecommendationOutcome], boolean>,
  'recordOutcomeV2' : ActorMethod<[RecommendationOutcomeV2], boolean>,
  'registerWhatsAppPhone' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'rejectCampaign' : ActorMethod<
    [string, string],
    { 'ok' : Campaign } |
      { 'err' : string }
  >,
  'requestChanges' : ActorMethod<
    [string, string],
    { 'ok' : Campaign } |
      { 'err' : string }
  >,
  'requestMarkdownConversion' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resetAllDriverMemory' : ActorMethod<[], undefined>,
  /**
   * / Admin only: reset all driver rate limit counters manually.
   */
  'resetAllRateLimits' : ActorMethod<[], undefined>,
  'resetNdunaEvolution' : ActorMethod<[], undefined>,
  'resumeAllCampaigns' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDriverPaymentConfig' : ActorMethod<[DriverPaymentConfig], undefined>,
  'saveFuelProfile' : ActorMethod<[number, string], undefined>,
  'saveMySnapScanMerchantId' : ActorMethod<[string], undefined>,
  'savePostingSchedule' : ActorMethod<[PostingSchedule], undefined>,
  'saveStakingRecord' : ActorMethod<[StakingRecord], undefined>,
  'saveVideoBrandingConfig' : ActorMethod<[BrandingConfig], undefined>,
  'sendLeadFollowupEmail' : ActorMethod<
    [string, string, string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'sendOnboardingEmail' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'sendPitchEmail' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'sendWebsiteByEmail' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'sendWeeklyBriefingEmail' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'sendWhatsAppMessage' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin only: set both Cloudflare AI Gateway URL and key in one call.
   */
  'setAIGatewayConfig' : ActorMethod<[string, string], undefined>,
  /**
   * / Admin only: set the Cloudflare AI Gateway API key.
   */
  'setAIGatewayKey' : ActorMethod<[string], undefined>,
  /**
   * / Admin only: set the Cloudflare AI Gateway URL.
   */
  'setAIGatewayUrl' : ActorMethod<[string], undefined>,
  'setAgentMailApiKey' : ActorMethod<[string], undefined>,
  /**
   * / Admin only: set Brian API key for natural language transaction guides.
   */
  'setBrianApiKey' : ActorMethod<[string], undefined>,
  'setBrowserbaseConfig' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin only: set CoinMarketCap API key for Fear & Greed index.
   */
  'setCMCApiKey' : ActorMethod<[string], undefined>,
  'setCamofoxBaseUrl' : ActorMethod<[string], undefined>,
  'setCampaignConfig' : ActorMethod<[CampaignConfig], boolean>,
  'setDocVaultNotesEnabled' : ActorMethod<
    [boolean],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'setDriverRouteOptIn' : ActorMethod<[SAZone, [] | [SAZone]], undefined>,
  'setEarningsGoal' : ActorMethod<[EarningsGoal], undefined>,
  'setElevenLabsApiKey' : ActorMethod<[string], undefined>,
  /**
   * / Admin only: store the Exa API key securely in the canister.
   * / Never returned in plain text — use getExaApiKey for a masked preview.
   */
  'setExaApiKey' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'setGoogleMapsApiKey' : ActorMethod<[string], undefined>,
  'setHermesConfig' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setHyperframesVpsKey' : ActorMethod<[string], undefined>,
  'setHyperframesVpsUrl' : ActorMethod<[string], undefined>,
  'setLeadFollowupEmailEnabled' : ActorMethod<[boolean], undefined>,
  'setOnboardingEmailEnabled' : ActorMethod<[boolean], undefined>,
  'setOpenClawApiKey' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setOpportunityHunterConfig' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  /**
   * / Admin only: set the Orbis API key (enables PQS pre-flight + Orbis LLM fallback).
   * / Set to empty string to disable both features.
   */
  'setOrbisApiKey' : ActorMethod<[string], undefined>,
  'setOrbisPublisherConfig' : ActorMethod<
    [OrbisListingConfig],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: enable or disable pilot mode.
   * / When pilot mode is on, all paid third-party outcalls are skipped (ElevenLabs,
   * / Whisper, Camofox, Upload-Post, 360dialog paid templates, Tavily paid tier) and
   * / OpenRouter is restricted to free-tier models only.
   */
  'setPilotMode' : ActorMethod<[boolean], { 'ok' : null } | { 'err' : string }>,
  'setReferralConfig' : ActorMethod<[ReferralConfig], undefined>,
  'setSchedulerConfig' : ActorMethod<
    [SchedulerConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setShortsVpsConfig' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setSnapScanConfig' : ActorMethod<[string, string, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setTavilyApiKey' : ActorMethod<[string], undefined>,
  'setTomTomApiKey' : ActorMethod<[string], undefined>,
  'setUploadPostConfig' : ActorMethod<[UploadPostConfig], undefined>,
  'setVideoWhisperConfig' : ActorMethod<[WhisperConfig__1], undefined>,
  'setWeeklyBriefingEmailEnabled' : ActorMethod<[boolean], undefined>,
  'setWeeklyBriefingEnabled' : ActorMethod<[boolean], undefined>,
  'setWhatsAppConfig' : ActorMethod<[WhatsAppConfig], undefined>,
  'setWhisperConfig' : ActorMethod<[WhisperConfig], undefined>,
  'setXApiKeys' : ActorMethod<
    [string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setXEarningsThreshold' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'submitShortsJob' : ActorMethod<
    [ShortsRequest],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'submitZeroXWorkTask' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'sync0xWorkEarnings' : ActorMethod<
    [],
    { 'ok' : ZeroXWorkEarnings } |
      { 'err' : string }
  >,
  /**
   * / Admin only: sync 0xWork earnings AND update the X posting threshold tracker.
   * / Wraps sync0xWorkEarnings() and then calls updateMonthlyXEarnings() with the
   * / latest cumulative USDC converted to cents (1 USDC = 100 cents).
   */
  'syncEarningsAndXThreshold' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'syncXPostMetrics' : ActorMethod<[], { 'ok' : bigint } | { 'err' : string }>,
  'tavilySearch' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin only: test the stored Exa API key by running a company research query.
   * / Returns a summary string (company name + snippet) on success, or an error message.
   */
  'testExaCompanyResearch' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'trigger0xWorkRegistration' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'triggerBrowserbaseHunt' : ActorMethod<
    [Principal],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'triggerLeadRefresh' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'triggerNdunaXPost' : ActorMethod<
    [XPostType],
    { 'ok' : XPost } |
      { 'err' : string }
  >,
  'triggerOpportunityHunt' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin only: trigger Orbis agent self-registration.
   * / Calls the Orbis discovery → register → subscribe flow and stores the returned
   * / sk_... API key into orbisApiKeyStore automatically on success.
   */
  'triggerOrbisRegistration' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'triggerReferralBonus' : ActorMethod<[string], [] | [string]>,
  'triggerTaskDiscovery' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'triggerVideoProcessing' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'triggerWeeklyBriefings' : ActorMethod<
    [],
    { 'sent' : bigint, 'failed' : bigint }
  >,
  'updateDriverMemory' : ActorMethod<[string, string], undefined>,
  'updateDriverRating' : ActorMethod<
    [number],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateLeadStatus' : ActorMethod<
    [string, LeadStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateMarkdownContent' : ActorMethod<
    [string, [] | [string], MarkdownStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateMonthlyXEarnings' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateNdunaSystemPrompt' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updatePitch' : ActorMethod<[string, CompanyPitch], boolean>,
  'updatePitchStatus' : ActorMethod<[string, PitchStatus], boolean>,
  'updateShortsJobStatus' : ActorMethod<
    [string, ShortsStatus, [] | [string], [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'uploadDocument' : ActorMethod<
    [string, DocumentType, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'upsertCompetitiveProfile' : ActorMethod<
    [string, number, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];